
import { PageLayout } from '@/components'

const Home = () => {
  return <PageLayout>
    Home
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. At repellendus obcaecati aspernatur, aperiam maxime vel optio. Debitis, vitae commodi sit sequi, distinctio, odit modi beatae possimus sed nemo repudiandae optio perspiciatis corporis quibusdam hic minus? Officiis deleniti sequi minus laborum, veritatis architecto libero similique pariatur et aliquid placeat labore omnis amet quod quos! Quidem debitis esse eveniet enim, corrupti voluptatibus obcaecati nisi amet, cum quo, aperiam rem voluptates eligendi optio libero minus harum facere. Iusto, doloribus! Non natus aperiam quas. Architecto, velit aliquam unde dicta perspiciatis eveniet odit officia animi, at iste reprehenderit similique, sed aspernatur. Repellendus rerum fuga doloribus ut laudantium suscipit enim repudiandae, tempore voluptatem reprehenderit, est dolorem id vitae quod delectus quasi, molestias eum ab molestiae ipsam libero cupiditate? Magni ipsam similique nobis corporis et eligendi fugit, modi perspiciatis hic nostrum sapiente consequatur officiis, voluptate cum, aliquam dolorem? Minus a obcaecati expedita, quam iste quia sed fuga? Voluptas quae quibusdam sed magnam unde, aut atque beatae? Iusto provident amet in aspernatur necessitatibus voluptate corporis ullam harum dicta, porro, accusamus itaque quasi laboriosam. Eaque, maiores dolorum! Vel modi error vero quidem atque adipisci mollitia, ab, officiis nostrum rerum itaque neque sed, iste iure temporibus hic praesentium amet soluta maxime odit qui deserunt. Dignissimos facilis explicabo soluta quis laudantium, unde ipsa accusantium sequi consectetur itaque voluptatem blanditiis doloremque fuga aliquid sunt quasi sint hic quo voluptates. Eum, iure ullam beatae, consectetur ratione fugiat, sequi corporis possimus est ipsam ipsum fuga iste tempore ex quidem accusamus voluptate rerum odio doloribus optio. Commodi placeat atque recusandae reprehenderit similique nesciunt eveniet dolor ullam in pariatur, unde aut nam quibusdam consequuntur quam esse ipsa tenetur accusamus doloribus eaque. Aliquid quaerat ex velit cum iure omnis voluptate eius porro, nihil numquam asperiores iste possimus maxime earum, veniam mollitia consequatur ducimus qui. Labore, officia mollitia!</p>
  </PageLayout>;
};

export default Home;
